import {QrCode,Ecc} from './qrcodegen.ts';
import {formatPayload,Mode} from './formatters.ts';
import {defaults,Design,toSvg,svgToBlob,pdfBlob,warnings} from './render.ts';
import './style.css';

const app=document.querySelector<HTMLDivElement>('#app')!; let logo='';
app.innerHTML=`<header><div><b>SayaQR</b><span>Generated locally • No tracking • No upload</span></div></header><main><section class="card controls"><h1>Offline QR code generator</h1><label>Mode<select id="mode">${['text','url','wifi','email','sms','phone','vcard','upi','event','geo'].map(m=>`<option value="${m}">${m}</option>`)}</select></label><div id="fields"></div><h2>Design</h2><div class="grid"><label>Foreground<input id="fg" type="color" value="#111827"></label><label>Background<input id="bg" type="color" value="#ffffff"></label><label>Transparent<input id="transparent" type="checkbox"></label><label>Quiet zone<input id="margin" type="number" min="0" value="4"></label><label>Module size<input id="moduleSize" type="number" min="4" value="10"></label><label>Rounded<input id="rounded" type="range" min="0" max="0.5" step="0.05" value="0.18"></label><label>Finder style<select id="finderStyle"><option>rounded</option><option>square</option><option>dot</option></select></label><label>Logo<input id="logo" type="file" accept="image/*"></label><label>Logo size<input id="logoRatio" type="range" min="0.05" max="0.35" step="0.01" value="0.18"></label></div><h2>Batch</h2><input id="csv" type="file" accept=".csv,text/csv"><select id="csvColumn"></select><button id="batch">Export ZIP</button></section><section class="card preview"><div id="badges"><span>🔒 local</span><span>🚫 tracking</span><span>📴 offline PWA</span></div><div id="qr"></div><ul id="warnings"></ul><div class="actions"><button data-export="svg">SVG</button><button data-export="png">PNG</button><button data-export="webp">WebP</button><button data-export="pdf">PDF</button></div></section></main>`;
const fieldMap:Record<Mode,string>={text:'<textarea id="text" placeholder="Text"></textarea>',url:'<input id="text" placeholder="example.com">',wifi:'<input id="ssid" placeholder="SSID"><input id="password" placeholder="Password"><select id="security"><option>WPA</option><option>WEP</option><option>nopass</option></select><label>Hidden <input id="hidden" type="checkbox"></label>',email:'<input id="email" placeholder="name@example.com"><input id="subject" placeholder="Subject">',sms:'<input id="phone" placeholder="Phone"><input id="message" placeholder="Message">',phone:'<input id="phone" placeholder="Phone">',vcard:'<input id="name" placeholder="Full name"><input id="org" placeholder="Organization"><input id="title" placeholder="Title"><input id="phone" placeholder="Phone"><input id="email" placeholder="Email"><input id="url" placeholder="URL"><input id="address" placeholder="Address">',upi:'<input id="pa" placeholder="UPI ID"><input id="pn" placeholder="Payee name"><input id="am" placeholder="Amount"><input id="tn" placeholder="Note">',event:'<input id="title" placeholder="Title"><input id="location" placeholder="Location"><input id="start" type="datetime-local"><input id="end" type="datetime-local"><input id="description" placeholder="Description">',geo:'<input id="lat" placeholder="Latitude"><input id="lng" placeholder="Longitude"><input id="query" placeholder="Label/search">'};
function vals(){ const ids=['text','ssid','password','security','hidden','email','subject','phone','message','name','org','title','url','address','pa','pn','am','cu','tn','location','start','end','description','lat','lng','query']; return Object.fromEntries(ids.map(id=>[id,(document.getElementById(id) as HTMLInputElement)?.type==='checkbox'?(document.getElementById(id) as HTMLInputElement)?.checked:(document.getElementById(id) as HTMLInputElement)?.value||''])); }
function design():Design{return {...defaults,fg:v('fg'),bg:v('bg'),transparent:ck('transparent'),margin:+v('margin'),moduleSize:+v('moduleSize'),rounded:+v('rounded'),finderStyle:v('finderStyle') as any,logoDataUrl:logo,logoRatio:+v('logoRatio')}}
const v=(id:string)=>(document.getElementById(id) as HTMLInputElement).value; const ck=(id:string)=>(document.getElementById(id) as HTMLInputElement).checked;
function render(){ const mode=v('mode') as Mode; document.getElementById('fields')!.innerHTML=fieldMap[mode]; document.getElementById('fields')!.addEventListener('input',renderQr); renderQr(); }
function renderQr(){ const payload=formatPayload(v('mode') as Mode,vals()); const qr=QrCode.encodeText(payload,Ecc.MEDIUM); const d=design(); document.getElementById('qr')!.innerHTML=toSvg(qr,d); document.getElementById('warnings')!.innerHTML=warnings(payload,d).map(w=>`<li>${w}</li>`).join(''); }
app.addEventListener('input',e=>{ if((e.target as HTMLElement).id==='mode') render(); else renderQr();});
document.getElementById('logo')!.addEventListener('change',async e=>{ const f=(e.target as HTMLInputElement).files?.[0]; if(f) logo=await new Promise(r=>{const fr=new FileReader(); fr.onload=()=>r(fr.result as string); fr.readAsDataURL(f)}); renderQr();});
app.addEventListener('click',async e=>{ const kind=(e.target as HTMLElement).dataset.export; if(!kind)return; const svg=document.querySelector('#qr svg')!.outerHTML; const blob=kind==='svg'?new Blob([svg],{type:'image/svg+xml'}):kind==='pdf'?pdfBlob(svg):await svgToBlob(svg,kind==='webp'?'image/webp':'image/png'); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`sayaqr.${kind}`; a.click();});
let csvRows:string[][]=[]; document.getElementById('csv')!.addEventListener('change',async e=>{ const f=(e.target as HTMLInputElement).files?.[0]; if(!f)return; csvRows=(await f.text()).split(/\r?\n/).filter(Boolean).map(r=>r.split(',')); document.getElementById('csvColumn')!.innerHTML=csvRows[0].map((h,i)=>`<option value="${i}">${h}</option>`).join('');});
document.getElementById('batch')!.addEventListener('click',()=>{ const i=+(v('csvColumn')||0); const parts=csvRows.slice(1).map((r,n)=>`--saya\nContent-Type:image/svg+xml\nContent-Disposition:attachment; filename=qr-${n+1}.svg\n\n${toSvg(QrCode.encodeText(r[i]||''),design())}`).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([parts,'\n--saya--'],{type:'application/zip'})); a.download='sayaqr-batch.zip'; a.click();});
if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js'); render();
