import {QrCode} from './qrcodegen.ts';
export type FinderStyle='square'|'rounded'|'dot';
export interface Design{fg:string;bg:string;transparent:boolean;margin:number;moduleSize:number;rounded:number;finderStyle:FinderStyle;logoDataUrl?:string;logoRatio:number}
export const defaults:Design={fg:'#111827',bg:'#ffffff',transparent:false,margin:4,moduleSize:10,rounded:.18,finderStyle:'rounded',logoRatio:.18};
export function contrastRatio(a:string,b:string){ const rgb=(h:string)=>{h=h.replace('#','');return [0,2,4].map(i=>parseInt(h.slice(i,i+2),16)/255).map(v=>v<=.03928?v/12.92:((v+.055)/1.055)**2.4)}; const la=rgb(a), lb=rgb(b); const L1=.2126*la[0]+.7152*la[1]+.0722*la[2], L2=.2126*lb[0]+.7152*lb[1]+.0722*lb[2]; return (Math.max(L1,L2)+.05)/(Math.min(L1,L2)+.05); }
export function warnings(payload:string,d:Design){ const out:string[]=[]; if(!d.transparent&&contrastRatio(d.fg,d.bg)<4.5) out.push('Contrast is too low for reliable scanning.'); if(d.margin<4) out.push('Quiet zone should be at least 4 modules.'); if(d.logoDataUrl&&d.logoRatio>.22) out.push('Logo is too large and may cover QR data.'); if(new TextEncoder().encode(payload).length>900) out.push('Data is very long; test scanning before publishing.'); return out; }
export function toSvg(qr:QrCode,d:Design=defaults){ const m=d.margin, ms=d.moduleSize, size=(qr.size+m*2)*ms, r=ms*d.rounded; let s=`<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">`; if(!d.transparent)s+=`<rect width="100%" height="100%" fill="${d.bg}"/>`; for(let y=0;y<qr.size;y++)for(let x=0;x<qr.size;x++)if(qr.getModule(x,y)){ const px=(x+m)*ms, py=(y+m)*ms; s+=`<rect x="${px}" y="${py}" width="${ms}" height="${ms}" rx="${r}" fill="${d.fg}"/>`; } if(d.logoDataUrl){ const l=size*d.logoRatio, p=(size-l)/2; s+=`<rect x="${p-6}" y="${p-6}" width="${l+12}" height="${l+12}" rx="12" fill="${d.transparent?'white':d.bg}"/><image href="${d.logoDataUrl}" x="${p}" y="${p}" width="${l}" height="${l}"/>`; } return s+'</svg>'; }
export async function svgToBlob(svg:string,type='image/png'){ const img=new Image(); const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'})); await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url}); const c=document.createElement('canvas'); c.width=img.width; c.height=img.height; c.getContext('2d')!.drawImage(img,0,0); URL.revokeObjectURL(url); return await new Promise<Blob>(r=>c.toBlob(b=>r(b!),type)); }
export function pdfBlob(svg:string){ return new Blob([`%PDF-1.1\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Count 1>>endobj\n% SayaQR embeds SVG separately\n${svg}\n%%EOF`],{type:'application/pdf'}); }
